# Generated by Django 5.1.4 on 2025-01-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullrequest', '0002_remove_prreview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='prreview',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
