# Generated by Django 5.1.4 on 2025-01-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullrequest', '0002_alter_prreview_total_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prreview',
            name='total_review',
            field=models.TextField(),
        ),
    ]
