# Generated by Django 5.1.4 on 2025-01-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullrequest', '0003_alter_prreview_total_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prreview',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
