global:
  resolve_timeout: 1m
  slack_api_url: "https://hooks.slack.com/services/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"
route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "slack-notifications"

receivers:
  - name: "slack-notifications"
    slack_configs:
      channel: "#alerts"
      send_resolved: true
      title: "{{ .GroupLabels.alertname }}"
      text: "{{ range .Alerts }}*Alert:* {{ .Annotations.summary }}\n*Description:* {{ .Annotations.description }}\n*Severity:* {{ .Labels.severity }}\n{{ end }}"
