# Generated by Django 5.1.4 on 2025-01-13 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partreview', '0002_remove_codereview_mode_remove_codereview_review_and_more'),
        ('user', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
