# Generated by Django 5.1.4 on 2025-01-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='report_report',
        ),
        migrations.AlterModelTable(
            name='reportprreview',
            table='report_prreview',
        ),
    ]
