global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "django"
    static_configs:
      - targets: ["django:8000"] # Nginx를 통해 Django 메트릭 수집
    metrics_path: "/metrics"

  - job_name: "nginx" # nginx-exporter 추가
    static_configs:
      - targets: ["nginx-exporter:9113"]
    metrics_path: "/metrics"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
