global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert-rules.yml" # 규칙 파일 추가

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093" # AlertManager 서비스 추가

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "django"
    static_configs:
      - targets: ["django:8000"] # Nginx를 통해 Django 메트릭 수집
    metrics_path: "/metrics"

  - job_name: "nginx" # nginx-exporter 추가
    static_configs:
      - targets: ["nginx-exporter:9113"]
    metrics_path: "/metrics"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    metrics_path: "/metrics"

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    metrics_path: "/metrics"
