# Generated by Django 5.1.4 on 2025-01-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='review_mode',
            field=models.CharField(choices=[('basic mode', 'Basic Mode'), ('clean mode', 'Clean Mode'), ('optimize mode', 'Optimize Mode'), ('new bie mode', 'New Bie Mode'), ('study mode', 'Study Mode')], default='basic mode', max_length=20),
        ),
    ]
