# Generated by Django 5.1.5 on 2025-01-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_review_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='review_mode',
            field=models.CharField(choices=[('basic', 'Basic'), ('clean', 'Clean'), ('optimize', 'Optimize'), ('newbie', 'NewBie'), ('study', 'Study')], default='clean', max_length=20),
        ),
    ]
