# Generated by Django 5.1.4 on 2025-01-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_userprofile_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('github_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('github_username', models.CharField(max_length=100)),
                ('acce₩ㅌss_token', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
