# Generated by Django 5.1.4 on 2025-01-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='review_mode',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('clean mode', 'Clean Mode'), ('optimize mode', 'Optimize Mode'), ('new bie mode', 'New Bie Mode'), ('study mode', 'Study Mode')], default='basic', max_length=20),
        ),
    ]
