# Generated by Django 5.1.4 on 2025-01-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_review_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='review_mode',
            field=models.CharField(choices=[('basic mode', 'Basic Mode'), ('clean mode', 'Clean Mode'), ('optimize mode', 'Optimize Mode'), ('new bie mode', 'New Bie Mode'), ('study mode', 'Study Mode')], default='Basic Mode', max_length=20),
        ),
    ]
