name: Deploy to Production

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GCP
        if: github.ref == 'refs/heads/deploy' && github.event_name == 'push'
        uses: appleboy/ssh-action@1.1.0
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            cd /home/syt47053052/review-Backend
            git pull origin deploy
            docker compose down
            docker compose up -d
